In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import scipy as sc
from sklearn import preprocessing
from sklearn import model_selection

from recsys import preprocess
from recsys import utility

RANDOM_STATE = 2342

%matplotlib inline

In [2]:
train = pd.read_csv('data/train_final.csv', delimiter='\t')
playlists = pd.read_csv('data/playlists_final.csv', delimiter='\t')
target_playlists = pd.read_csv('data/target_playlists.csv', delimiter='\t')
target_tracks = pd.read_csv('data/target_tracks.csv', delimiter = '\t')
tracks = pd.read_csv('data/tracks_final.csv', delimiter='\t')

In [3]:
train, test = model_selection.train_test_split(train, test_size=0.20, random_state=RANDOM_STATE)

In [8]:
small_train = train.loc[1:1000,:]

In [12]:
s = small_train.groupby('track_id')

In [22]:
a = s.count()

In [27]:
a.sort_values('playlist_id', ascending=False, inplace=True)

In [234]:
df.to_csv?

In [39]:
a = pd.DataFrame(columns=['a', 'b'])

In [ ]:
train = get_train()
target_playlist = get_target_playlists()
target_tracks = get_target_tracks()

train, test = model_selection.train_test_split(train, test_size=0.20, random_state=RANDOM_STATE)

In [29]:
most_popular = get_most_popular_tracks(train)
tracks_in_playlist = get_playlist_track_list(train)

In [32]:
most_popular = most_popular.index.values

In [41]:
from recsys.preprocess import *
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import scipy as sc
from sklearn import preprocessing
from sklearn import model_selection

RANDOM_STATE = 42

tracks_to_suggest = np.intersect1d(most_popular, target_tracks)
predictions = []

for it,row in target_playlist.iterrows():
    count = 0
    i = 0
    pred = []
    while count < 5:
        if tracks_to_suggest[i] not in tracks_in_playlist[row['playlist_id']]:
            # Predict track i
            pred.append(most_popular[i])
            count += 1
        i += 1
    predictions.append(' '.join(map(str, pred)))

In [43]:
results = pd.DataFrame(np.transpose([target_playlist['playlist_id'].values, predictions]), columns=['playlist_id', 'track_ids'])

In [46]:
len(test)

208105

In [47]:
from recsys.utility import *

In [48]:
def evaluate(test, recommendations):
    test_good = preprocess.get_playlist_track_list(test)

    mean_ap = 0
    for pl_id, tracks in recommendations:
        correct = 0
        ap = 0
        for it, t in enumerate(tracks):
            if t in test_good[pl_id]:
                correct += 1
                ap += correct / (it+1)
        ap /= len(tracks)
        mean_ap += ap

    return mean_ap / len(recommendations)


In [80]:
recomm = np.array([list(map(int,x.split(' '))) for x in results['track_ids'].values])

In [81]:
recomm

array([[1563309, 1363985, 3705881, 1595978, 3779477],
       [1563309, 1363985, 3705881, 1595978, 3779477],
       [1563309, 1363985, 3705881, 1595978, 3779477],
       ..., 
       [1563309, 1363985, 3705881, 1595978, 3779477],
       [1563309, 1363985, 3705881, 1595978, 3779477],
       [1563309, 1363985, 3705881, 1595978, 3779477]])

In [82]:
evaluate(test, recomm)

ValueError: too many values to unpack (expected 2)

In [225]:
def train_test_split(train, test_size=0.3):
    playlists = train.groupby('playlist_id').count()
    to_choose_playlists = playlists[playlists['track_id'] > 7].index.values
    target_playlists = np.random.choice(to_choose_playlists, replace=False, size=int(test_size * len(to_choose_playlists)))
    
    target_tracks = np.array([])
    indexes = np.array([])
    for p in target_playlists:
        selected_df = train[train['playlist_id'] == p].sample(5)
        selected_tracks = selected_df['track_id'].values
        target_tracks = np.union1d(target_tracks, selected_tracks)
        indexes = np.union1d(indexes, selected_df.index.values)
    
    test = df.loc[indexes].copy()
    train = train.drop(indexes)
    
    return train, test, target_playlists, target_tracks
    

In [226]:
x,y,z,w = train_test_split(train)

In [227]:
len(train)

832417

In [228]:
len(x)

798407

In [229]:
len(y)

34010

In [230]:
len(z)

6802

In [231]:
len(w)

24281

In [233]:
len(y)/len(x)

0.04259732191726776

In [235]:
df.to_csv?

In [237]:
train[train['track_id'] == 252]

playlist_id  track_id
269276      10550126       252
115607       8283678       252
999950       4322356       252
1007372      5554934       252
477645       1404694       252
405463       6102596       252
78094        7996678       252
701585       3853994       252
268901      11355891       252
590443       7333844       252
724078       7551236       252

In [238]:
most_popular = get_most_popular_tracks(train)

In [243]:
target_tracks['track_id'].values

array([1316175, 3885714, 3091270, ..., 2739213, 2228646, 2265463])

In [251]:
len(np.intersect1d(most_popular.index.values[:10], target_tracks['track_id'].values))

10

In [247]:
len(target_tracks['track_id'])

32195

In [249]:
len(most_popular.index)

99789

In [11]:
playlists_id = train['playlist_id'].drop_duplicates()

In [19]:
%%time
x = playlists_id.apply(lambda x : train[train['playlist_id'] == x]['track_id'].values)

CPU times: user 53.5 s, sys: 202 ms, total: 53.7 s
Wall time: 53.7 s


In [24]:
train.iloc[:10].groupby('playlist_id')['track_id'].apply(lambda x : print(x))

9    863177
Name: 886396, dtype: int64
0    2801526
Name: 3271849, dtype: int64
6    1166185
Name: 3794808, dtype: int64
4    2945623
Name: 3836898, dtype: int64
5    2821391
Name: 5270369, dtype: int64
1    727878
Name: 5616275, dtype: int64
7    2498280
Name: 7908370, dtype: int64
3    1515105
Name: 10103900, dtype: int64
2    2805283
Name: 11267488, dtype: int64
8    282687
Name: 11460733, dtype: int64


playlist_id
886396      None
3271849     None
3794808     None
3836898     None
5270369     None
5616275     None
7908370     None
10103900    None
11267488    None
11460733    None
Name: track_id, dtype: object

In [3]:
from recsys.preprocess import *
from sklearn import model_selection
import numpy as np
from recsys.utility import *

RANDOM_STATE = 42

train = get_train()
#target_playlist = get_target_playlists()
#target_tracks = get_target_tracks()



train, test, target_playlist, target_tracks = train_test_split(train)

most_popular = get_most_popular_tracks(train)
tracks_in_playlist = get_playlist_track_list(train)


tracks_to_suggest = most_popular.index.values
predictions = []
test_pred = []
for it,row in enumerate(target_playlist):
    count = 0
    i = 0
    pred = []
    while count < 5:
        if tracks_to_suggest[i] not in tracks_in_playlist[row]:
            # Predict track i
            pred.append(tracks_to_suggest[i])
            count += 1
        i += 1
    test_pred.append(pred[:])
    predictions.append(' '.join(map(str, pred)))

res = evaluate(test, predictions)

results = pd.DataFrame(np.transpose([target_playlist, predictions]), columns=['playlist_id', 'track_ids'])

results.to_csv('results.csv', index=False)


ValueError: too many values to unpack (expected 2)

playlist_id
7569        [2634448, 2693660, 2227105, 2654612, 162463, 1...
7614        [2285204, 1384962, 3711434, 1714787, 2141817, ...
7641        [3825235, 257968, 3711129, 1341128, 3502548, 2...
7692        [3036454, 1439032, 302730, 384386, 1559442, 21...
7816        [2305305, 1039409, 2674817, 126414, 2350576, 2...
7912        [126424, 218197, 3767380, 3560026, 2999747, 38...
7951                              [2448544, 2279578, 2273823]
7966                      [2719853, 3067297, 1156143, 515031]
8000                                                 [268908]
8071             [1942235, 1826140, 489605, 3454440, 1632666]
8143        [2020026, 2881153, 2424505, 641826, 2456355, 3...
8193        [2160453, 2953444, 1180165, 1885715, 99100, 45...
8225        [2285204, 1891198, 3102263, 1464491, 2800858, ...
8268        [4906479, 2247725, 1708008, 3667207, 3289000, ...
8275                              [2805555, 3293060, 3854357]
8337        [1210884, 1157460, 1205536, 451881, 3131838, 3

In [131]:
a = np.array([1, 2, 3, 4, 5])

In [139]:
np.union1d(a,b)

array([      3,       4,       5,       6,       7,       8,  252429,
       1952325])

In [152]:
a = df.loc[[518209, 598021]]

In [157]:
len(df.drop([518209]))

832416

In [158]:
len(df)

832417

In [128]:
train[train['playlist_id'] == 6226465].sample(5)['track_id'].values

array([3667257, 2765634, 3001336, 3477637, 1277686])

In [117]:
len(to_choose_playlists)

18337

In [92]:
a = (train.groupby('playlist_id').count())

In [101]:
a[a['track_id'] > 10].index.values

array([    7692,     7816,     7912, ..., 11764165, 11764751, 11764851])

In [38]:
len(target_tracks)

32195

In [39]:
len(most_popular)

99789

In [40]:
len(np.intersect1d(target_tracks, most_popular))

32074

In [6]:
a = sc.sparse.random(100000, 100000, density=0.0001)

In [7]:
a

<100000x100000 sparse matrix of type '<class 'numpy.float64'>'
	with 1000000 stored elements in COOrdinate format>

In [9]:
%%time
a.tocsc()

CPU times: user 6 ms, sys: 1.68 ms, total: 7.68 ms
Wall time: 6.35 ms


<100000x100000 sparse matrix of type '<class 'numpy.float64'>'
	with 1000000 stored elements in Compressed Sparse Column format>

In [10]:
import random

In [11]:
100000*100000*0.001

10000000.0

In [37]:
m = sc.sparse.coo_matrix((100000,100000))

In [38]:
data = sorted([(random.randint(0,100000-1), random.randint(0,100000-1)) for i in range(1000000)])

In [39]:
for x,y in data:
    m[x,y] = 1

TypeError: 'coo_matrix' object does not support item assignment

In [43]:
m.row = np.array([x[0] for x in data])
m.col = np.array([y[0] for y in data])
m.data = np.array([1 for x in data])

In [46]:
rrr = m.tocsr()

In [36]:
sc.sparse.coo_matrix?

In [19]:
m2 = sc.sparse.lil_matrix((100000,100000))

In [23]:
sc.sparse.lil_matrix?

In [28]:
m

<100000x100000 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in LInked List format>

In [56]:
rrr.tocsc()

<100000x100000 sparse matrix of type '<class 'numpy.int64'>'
	with 1000000 stored elements in Compressed Sparse Column format>